"""WFO aggregation, gate, and live-overrides emission."""
from __future__ import annotations
import json
import logging
import math
import os
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import yaml

logger = logging.getLogger(__name__)


@dataclass
class GateConfig:
    wfe_min: float = 0.5
    require_positive_oos_pnl: bool = True


def aggregate_results(results: pd.DataFrame, gate: GateConfig) -> pd.DataFrame:
    """For each (symbol, timeframe, setup): pick per-walk IS-best, compute WFE,
    apply gate. Returns one row per group with aggregate stats + pass/fail."""
    ok = results[results["status"] == "ok"]
    if ok.empty:
        return pd.DataFrame(columns=[
            "symbol", "timeframe", "setup", "walks",
            "sum_is_sharpe", "sum_oos_sharpe", "wfe",
            "total_oos_pnl", "mean_oos_sharpe", "passed",
            "winning_fingerprint_last_walk",
        ])

    # Per-walk IS-best within each (symbol, timeframe, setup)
    keys = ["symbol", "timeframe", "setup"]
    winners = (
        ok.sort_values("is_sharpe", ascending=False)
          .groupby(keys + ["walk_idx"], as_index=False)
          .head(1)
    )

    rows = []
    for (sym, tf, stp), g in winners.groupby(keys):
        g = g.sort_values("walk_idx")
        sum_is = float(g["is_sharpe"].sum())
        sum_oos = float(g["oos_sharpe"].sum())
        total_oos_pnl = float(g["oos_pnl"].sum())
        wfe = sum_oos / sum_is if sum_is > 0 else math.nan
        passed = (
            (not math.isnan(wfe))
            and (wfe >= gate.wfe_min)
            and ((total_oos_pnl > 0) if gate.require_positive_oos_pnl else True)
        )
        last_walk_winner = g.iloc[-1]["fingerprint"]
        rows.append({
            "symbol": sym, "timeframe": tf, "setup": stp,
            "walks": int(len(g)),
            "sum_is_sharpe": sum_is, "sum_oos_sharpe": sum_oos,
            "wfe": wfe, "total_oos_pnl": total_oos_pnl,
            "mean_oos_sharpe": float(g["oos_sharpe"].mean()),
            "passed": passed,
            "winning_fingerprint_last_walk": last_walk_winner,
        })
    df_out = pd.DataFrame(rows, dtype=object)
    # Restore proper dtypes for numeric columns, but keep 'passed' as object (Python bool)
    for col in ["walks", "sum_is_sharpe", "sum_oos_sharpe", "wfe", "total_oos_pnl", "mean_oos_sharpe"]:
        if col in df_out.columns:
            if col == "wfe":
                df_out[col] = df_out[col].astype(float)
            else:
                df_out[col] = pd.to_numeric(df_out[col])
    return df_out


def _atomic_write(path: Path, payload: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(payload)
    os.replace(tmp, path)


def emit_live_overrides(
    aggregated: pd.DataFrame,
    last_walk_combos: dict[str, tuple[dict, dict]],
    out_path: Path,
    *,
    run_id: str,
    git_sha: str,
    gate: GateConfig,
) -> None:
    """Per symbol, choose the highest mean_oos_sharpe among passed groups,
    tie-break on sorted (timeframe, setup). Emit YAML."""
    passed = aggregated[aggregated["passed"]].copy()
    symbols: dict[str, dict] = {}
    if not passed.empty:
        passed = passed.sort_values(
            ["mean_oos_sharpe", "timeframe", "setup"],
            ascending=[False, True, True],
        )
        for sym, g in passed.groupby("symbol"):
            winner = g.iloc[0]
            fp = winner["winning_fingerprint_last_walk"]
            if fp not in last_walk_combos:
                logger.warning("MISSING_LAST_WALK_COMBO symbol=%s fp=%s", sym, fp)
                continue
            setup_values, pm_values = last_walk_combos[fp]
            symbols[sym] = {
                "timeframe": str(winner["timeframe"]),
                "setup": str(winner["setup"]),
                "setup_params": setup_values,
                "position_management": pm_values,
                "metadata": {
                    "walks": int(winner["walks"]),
                    "mean_oos_sharpe": float(winner["mean_oos_sharpe"]),
                    "wfe": float(winner["wfe"]),
                    "total_oos_pnl": float(winner["total_oos_pnl"]),
                },
            }

    header = (
        f"# Generated by scripts/run_wfo.py\n"
        f"# run_id: {run_id}\n"
        f"# git_sha: {git_sha}\n"
        f"# wfe_min: {gate.wfe_min}  "
        f"require_positive_oos_pnl: {gate.require_positive_oos_pnl}\n"
        f"# gate-passed: {len(symbols)} of {aggregated['symbol'].nunique()} "
        f"evaluated symbols\n\n"
    )
    body = yaml.safe_dump({"symbols": symbols}, sort_keys=True, default_flow_style=False)
    _atomic_write(out_path, header + body)


def emit_summary_md(aggregated: pd.DataFrame, out_path: Path, *,
                    run_id: str, git_sha: str, gate: GateConfig) -> None:
    lines = [
        f"# WFO Run {run_id}\n",
        f"- git_sha: `{git_sha}`",
        f"- gate: WFE ≥ {gate.wfe_min}, "
        f"require_positive_oos_pnl: {gate.require_positive_oos_pnl}",
        f"- evaluated symbols: {aggregated['symbol'].nunique()}",
        f"- gate-passed groups: {int(aggregated['passed'].sum())}",
        "",
        "| symbol | timeframe | setup | walks | mean OOS Sharpe | WFE | total OOS P&L | passed |",
        "|---|---|---|---:|---:|---:|---:|:-:|",
    ]
    sorted_df = aggregated.sort_values(
        ["passed", "mean_oos_sharpe"], ascending=[False, False],
    )
    for _, r in sorted_df.iterrows():
        wfe = "—" if math.isnan(r["wfe"]) else f"{r['wfe']:.3f}"
        lines.append(
            f"| {r['symbol']} | {r['timeframe']} | {r['setup']} | "
            f"{int(r['walks'])} | {r['mean_oos_sharpe']:.3f} | {wfe} | "
            f"{r['total_oos_pnl']:.2f} | "
            f"{'✓' if r['passed'] else '✗'} |"
        )
    _atomic_write(out_path, "\n".join(lines) + "\n")


def update_latest_symlink(latest: Path, target: Path) -> None:
    """Atomically point `latest` symlink at `target` (relative)."""
    latest.parent.mkdir(parents=True, exist_ok=True)
    tmp = latest.with_suffix(latest.suffix + ".tmp_link")
    if tmp.is_symlink() or tmp.exists():
        tmp.unlink()
    tmp.symlink_to(target.relative_to(latest.parent), target_is_directory=True)
    os.replace(tmp, latest)


def update_latest_symlink_if_passing(latest: Path, target: Path,
                                     aggregated: pd.DataFrame) -> bool:
    """Only swap `latest` when the run produced at least one passing row."""
    if aggregated["passed"].any():
        update_latest_symlink(latest, target)
        return True
    logger.info("LATEST_NOT_UPDATED reason=zero_passing_groups")
    return False
